// <auto-generated />
namespace Parser_1a.lv.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Phones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Phones));
        
        string IMigrationMetadata.Id
        {
            get { return "201601211727399_Phones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
